global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'ltapp'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ltapp:8080']
        labels:
          application: 'LT app'

  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['node-exporter:9100']
  #       labels:
  #         application: 'LT server'